version: '3'
services:
  ubuntu:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../:/workspace:cached

    command: /bin/sh -c "while sleep 1000; do :; done"

  plantuml-server:
    image: plantuml/plantuml-server:jetty
    container_name: plantuml-server
    environment:
      - TZ=Australia/Perth
    
    ports:
      - "8080:8080"
